# Generated by Django 3.2.5 on 2021-08-23 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materials',
            options={'verbose_name': 'Материалы', 'verbose_name_plural': 'Материалы'},
        ),
    ]
